name: nux_wallpapers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  bubble_bottom_bar: ^1.2.0
  dio: any
  path_provider:
  flutter_bloc:
  bloc:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/n2.png
   - assets/loading.gif

  fonts:
    - family: Sans
      fonts:
        - asset: assets/Product-Sans-Regular.ttf